documentation: Add basic library documentation
xlcteam/PixyViSy pull request #16
Opened 2017-09-29 16:14 UTC by vargac

* Code documentation - mainly the interface
* Model and algorithm description

Signed-off-by: vargac <simon.varga123@gmail.com>

2018-01-28 08:05 UTC, vargac commented
@mrshu Could you have a look at it? Or should I request a review from someone else, or just merge by myself?

2018-01-29 13:09 UTC, mrshu commented
Sorry for ingoring this @vargac.

@Adman would you happen to have some time to review this? If not, I'll try my best to take a look but no sooner than next week -- sorry about that.

2018-02-10 21:08 UTC, Adman requested changes
@vargac Just small nitpicks to fix. Otherwise it looks good to me.

2018-02-10 21:08 UTC, Adman commented on PixyViSy.cpp
> +    if (ball.width > ball.height) { // prevent covered ball (e.g. by robot)
Put comment before `if` statement, and also between /* and */

2018-02-10 21:08 UTC, Adman commented on PixyViSy.cpp
> +
Remove empty line

2018-02-10 21:08 UTC, Adman commented on PixyViSy.h
> +           what will be processed in "update" function */
Please, describe a bit better what can be processed in update function according to `flag` argument. (and maybe what values can we set flag to)

2018-02-19 20:06 UTC, vargac commented on PixyViSy.h
> +           what will be processed in "update" function */
What can be processed is described in README, so I don't have to repeat it, do I?

2018-02-19 20:13 UTC, Adman approved these changes

2018-02-19 20:14 UTC, merged